/**
 * bfields — the TypeScript dependency engine must agree with the PHP one.
 *
 * The fixture is generated by tests/php/dump-dependencies.php from every
 * `dependency` rule any bPlugins plugin registers with Codestar on a real
 * install, with its `expected` column filled in by \BFields\Dependency.
 *
 * Phase 1 does not exit until this is green (plan, Phase 1 exit criteria): the
 * two engines are written twice on purpose (7.15), so the only thing keeping
 * them honest is this table.
 */

import { isVisible, evaluate, shown } from '../../ui/core/dependency';
import type { DependencyRule, Values } from '../../ui/core/types';
import cases from '../fixtures/dependency-cases.json';
import staleCases from '../fixtures/stale-select-cases.json';
import mixedCases from '../fixtures/mixed-scope-cases.json';

type Case = {
	rules: DependencyRule[];
	values: Values | Record<string, never>;
	row: Values | Record<string, never>;
	expected: boolean;
	origin: string;
};

const table = cases.cases as unknown as Case[];

describe('dependency engine parity with PHP', () => {
	it('has a non-trivial fixture', () => {
		expect(table.length).toBeGreaterThan(1000);
		// A table where everything is visible would pass vacuously.
		expect(table.some((c) => c.expected === false)).toBe(true);
		expect(table.some((c) => c.expected === true)).toBe(true);
	});

	it('agrees with the PHP engine on every case', () => {
		const disagreements: string[] = [];

		table.forEach((testCase, index) => {
			const row = Object.keys(testCase.row).length > 0 ? (testCase.row as Values) : undefined;
			const actual = isVisible(testCase.rules, testCase.values as Values, row);

			if (actual !== testCase.expected) {
				disagreements.push(
					`#${index} ${testCase.origin}: ` +
						`${JSON.stringify(testCase.rules)} against ` +
						`values=${JSON.stringify(testCase.values)} row=${JSON.stringify(testCase.row)} ` +
						`— PHP says ${testCase.expected}, TS says ${actual}`
				);
			}
		});

		expect(disagreements.slice(0, 20)).toEqual([]);
		expect(disagreements).toHaveLength(0);
	});
});

describe('Codestar operator semantics', () => {
	// The coercion table from assets/js/plugins.js (checkBoolean).
	it.each([
		['==', '1', true, true],
		['==', '1', '1', true],
		['==', '1', 1, true],
		['==', '1', 'true', true],
		['==', '0', '', true],
		['==', '0', false, true],
		['==', '0', null, true],
		['!=', '1', '0', true],
		['==', 'info', 'info', true],
		['==', 'info', 'link', false],
		// The loose-equality cases. CSF compares with `==`, so a switcher that
		// was never toggled (stored '') satisfies a `== '0'` rule — strict
		// equality would hide the field on exactly those records (3.1).
		['==', '0', '', true],
		['!=', '0', '', false],
		['==', '1', '', false],
		// PHP's own `==` would call this true (it casts the string to bool);
		// JavaScript's gives false. Both engines must give false.
		['==', '1', 'abc', false],
	])('%s %s against %p -> %p', (condition, value, current, expected) => {
		expect(evaluate(condition, value as string, current as never)).toBe(expected);
	});

	// Numeric operators read "current <op> ruleValue", matching CSF's
	// Number(val2) >= Number(val1).
	it.each([
		['>', '5', '10', true],
		['>', '5', '2', false],
		['>=', '5', '5', true],
		['<', '5', '2', true],
		['<=', '5', '5', true],
	])('%s %s against %s -> %p', (condition, value, current, expected) => {
		expect(evaluate(condition, value as string, current as never)).toBe(expected);
	});

	it('treats `any` as membership of the rule list', () => {
		expect(evaluate('any', 'a,b,c', 'b')).toBe(true);
		expect(evaluate('any', 'a,b,c', 'z')).toBe(false);
	});

	it('reproduces the `not-any` quirk for list values', () => {
		// CSF returns true as soon as ONE member is missing from the list, so a
		// multi-value controller can satisfy `any` and `not-any` at once. This
		// is deliberate parity, not an oversight (7.9).
		expect(evaluate('not-any', 'a', ['a', 'b'] as never)).toBe(true);
		expect(evaluate('any', 'a', ['a', 'b'] as never)).toBe(true);
		expect(evaluate('not-any', 'a,b', ['a', 'b'] as never)).toBe(false);
	});

	it('never hides a field for a rule it cannot evaluate', () => {
		expect(evaluate('()', 'someGlobalFn', '')).toBe(true);
		expect(evaluate('unknown-operator', 'x', 'x')).toBe(false);
	});
});

describe('scope resolution', () => {
	const rule = (scope: 'local' | 'global'): DependencyRule[] => [
		{ controller: 'type', condition: '==', value: 'link', scope },
	];

	it('resolves a local controller from the row first', () => {
		expect(isVisible(rule('local'), { type: 'info' }, { type: 'link' })).toBe(true);
	});

	it('falls back to the root when the row has no such key', () => {
		expect(isVisible(rule('local'), { type: 'link' }, { other: '1' })).toBe(true);
	});

	it('skips the row entirely for a global rule', () => {
		// This is Codestar's 4th `'all'` element, and the reason the hotspot
		// link-field rule no longer needs a body-class hack.
		expect(isVisible(rule('global'), { type: 'link' }, { type: 'info' })).toBe(true);
		expect(isVisible(rule('global'), { type: 'info' }, { type: 'link' })).toBe(false);
	});
});

describe('stale single-select controllers (V-M4)', () => {
	type StaleCase = { rules: DependencyRule[]; values: Values; row: Values; expected: boolean; origin: string };

	// tests/php/schema.php replays the same table through \BFields\Dependency.
	it.each((staleCases.cases as unknown as StaleCase[]).map((c) => [c.origin, c] as const))('%s', (_origin, c) => {
		const row = Object.keys(c.row).length > 0 ? c.row : undefined;

		expect(isVisible(c.rules, c.values, row)).toBe(c.expected);
	});

	it('maps only the value the rule reads, never the stored one', () => {
		const rule: DependencyRule = { controller: 't', condition: '==', value: 'none', scope: 'local', choices: ['none'], shown: 'none' };

		expect(shown(rule, '')).toBe('none');
		expect(shown(rule, 'none')).toBe('none');
		expect(shown({ ...rule, choices: undefined }, '')).toBe('');
	});
});

describe('mixed-scope rule sets (one local rule AND one global rule)', () => {
	type MixedCase = { rules: DependencyRule[]; values: Values; row: Values; expected: boolean; origin: string };

	// tests/php/dependency-replay.php replays the same table through \BFields\Dependency.
	it.each((mixedCases.cases as unknown as MixedCase[]).map((c) => [c.origin, c] as const))('%s', (_origin, c) => {
		const row = Object.keys(c.row).length > 0 ? c.row : undefined;

		expect(isVisible(c.rules, c.values, row)).toBe(c.expected);
	});
});
